#!/bin/bash
echo Start deploying portfolio...
echo Install dependencies...
npm install --production
echo Build website...
npm run build
echo Delete server old files...
rm /var/www/victorcazanave.com/*
rm -r /var/www/victorcazanave.com/css
rm -r /var/www/victorcazanave.com/js
echo Copy new files to server...
cp ~/git/portfolio/dist/* /var/www/victorcazanave.com/
cp -R ~/git/portfolio/dist/css /var/www/victorcazanave.com/
cp -R ~/git/portfolio/dist/js /var/www/victorcazanave.com/
echo portfolio has been deployed!
