#!/bin/bash
echo Start deploying portfolio...
cd ~/git/portfolio/
echo Install dependencies...
npm install
echo Build website...
npm run build
echo Copy files to server...
cp ~/git/portfolio/build/* /var/www/
echo Copy svg folder to server...
cp -R ~/git/portfolio/build/svg /var/www/
echo portfolio has been deployed!
